### ISSUE TITLE
"Embracing variability in the search for biological mechanisms of psychiatric illness"

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/reproducibility-biblio.github.io#1]
On the question of generalizability

Looking for a little reading on your way home from [#ohbm2024](https://x.com/search?q=%23ohbm2024&src=hash)? Our ([⁦‪@JegTiego‬⁩](https://x.com/JegTiego) [⁦‪@LindenParkes‬⁩](https://x.com/LindenParkes) [⁦‪@AvramHolmes‬⁩](https://x.com/AvramHolmes) [⁦‪@amarquand‬⁩](https://x.com/amarquand) [⁦‪@AFornito‬⁩](https://x.com/AFornito)) latest preprint argues that embracing variability is essential to uncover the biological mechanisms of psychiatric illness 🧵/1

[osf.io/preprints/osf/…](https://t.co/Y8bFvSfbv6)
 
[27/6/24, 13:06](https://x.com/ashleasegal/status/1806282980152971440?s=43&t=k_kPqxXHqRxWFNtjwUJZaA)

**Comment by alexpron** [comment]
I manually added the reference in Zotero and then exported the whole zotero bibliography into the publication directory similar to Hugo Block format. The reference hence is present in the website.

**Comment by cmaumet** [comment]
@alexpron - there is no rush but when we are both in, let's look into this together. (I did not follow which website you are referring to in your last message).
